-- zhCN 本地化

local function GWUseThisLocalization()

-- 创建语言字符串的全局变量
GwLocalization = {}

-- 设置
GwLocalization['SETTINGS_TITLE'] = '设置'
GwLocalization['MOVE_HUD_BUTTON'] = '移动界面'
GwLocalization['SETTINGS_RESET_TO_DEFAULT'] = '重置为默认.'
GwLocalization['SETTINGS_ACCEPT'] = '接受'
GwLocalization['SETTINGS_CANCEL'] = '取消'
GwLocalization['SETTINGS_VERSION'] = '版本'
GwLocalization['SETTINGS_SAVE_RELOAD'] = '保存并重新加载'
GwLocalization['SETTINGS_DELETE'] = '删除'
GwLocalization['SETTINGS_ACTIVATE'] = '启用'
GwLocalization['SETTINGS_BUTTON'] = 'GW2 UI设置'
GwLocalization['SETTING_LOCK_HUD'] = '锁定界面'

GwLocalization['MODULES_CAT'] = '模块'
GwLocalization['MODULES_CAT_1'] = '模块' 
GwLocalization['MODULES_CAT_TOOLTIP']= '启用或禁用模块'
GwLocalization['MODULES_DESC'] = '启用需要的模块或禁用不需要的模块.'
GwLocalization['MODULES_TOOLTIP'] = '启用或禁用界面模块.'
GwLocalization['HEALTH_GLOBE'] = '玩家血球'
GwLocalization['RESOURCE'] = '能量'
GwLocalization['FOCUS_FRAME'] = '焦点'
GwLocalization['TARGET_FRAME'] = '目标'
GwLocalization['CHAT_BUBBLES'] = '聊天气泡'
GwLocalization['MINIMAP'] = '小地图'
GwLocalization['QUEST_TRACKER'] = '任务追踪'
GwLocalization['TOOLTIPS'] = '鼠标提示'
GwLocalization['CHAT_FRAME'] = '聊天框'
GwLocalization['QUESTING_FRAME'] = '沉浸式任务'
GwLocalization['PLAYER_AURAS'] = '玩家光环'
GwLocalization['ACTION_BARS'] = '动作条'
GwLocalization['INVENTORY_FRAME'] = '背包'
GwLocalization['FONTS'] = '字体'
GwLocalization['CASTING_BAR'] = '施法条'
GwLocalization['CLASS_POWER'] = '连击点'
GwLocalization['GROUP_FRAMES'] = '团队'
GwLocalization['CHARACTER_WINDOW'] = '角色信息' 

GwLocalization['TARGET_CAT'] = '目标'
GwLocalization['TARGET_CAT_1'] = '目标' 
GwLocalization['TARGET_DESC'] = '修改目标模块设置.'
GwLocalization['TARGET_TOOLTIP'] = '目标模块设置'
GwLocalization['TARGET_OF_TARGET'] = '目标的目标'
GwLocalization['HEALTH_VALUE'] = '血量数值'
GwLocalization['HEALTH_PERCENTAGE'] = '血量百分比'
GwLocalization['CLASS_COLOR'] = '职业颜色'
GwLocalization['SHOW_DEBUFFS'] = '显示Debuffs'
GwLocalization['SHOW_ALL_DEBUFFS'] = '显示所有Debuffs'
GwLocalization['SHOW_BUFFS'] = '显示Buffs'

GwLocalization['FOCUS_CAT'] = '焦点'
GwLocalization['FOCUS_CAT_1'] = '焦点' 
GwLocalization['FOCUS_DESC'] = '修改焦点模块设置.'
GwLocalization['FOCUS_TOOLTIP'] = '焦点模块设置'
GwLocalization['FOCUS_TARGET'] = '焦点目标'

GwLocalization['HUD_CAT'] = '界面'
GwLocalization['HUD_CAT_1'] = '界面' 
GwLocalization['HUD_DESC'] = '修改界面模块进行更多的个性化设置.'
GwLocalization['HUD_TOOLTIP'] = '界面模块设置.'
GwLocalization['ACTION_BAR_FADE'] = '渐隐动作条'
GwLocalization['DYNAMIC_HUD'] = '动态界面'
GwLocalization['CHAT_FADE'] = '渐隐聊天框'
GwLocalization['HIDE_EMPTY_SLOTS'] = '隐藏空动作栏'
GwLocalization['COMPASS_TOGGLE'] = '切换指南针'
GwLocalization['ADV_CAST_BAR'] = '高级施法条'
GwLocalization['HUD_SCALE'] = '界面缩放'
    GwLocalization['HUD_SCALE_DEFAULT'] = '默认'
    GwLocalization['HUD_SCALE_SMALL'] = '小型'
    GwLocalization['HUD_SCALE_TINY'] = '微型'
GwLocalization['MINIMAP_SCALE'] = '小地图缩放'
    GwLocalization['MINIMAP_SCALE_LARGE'] = '大型'
    GwLocalization['MINIMAP_SCALE_MEDIUM'] = '中等'
    GwLocalization['MINIMAP_SCALE_DEFAULT'] = '默认'

GwLocalization['GROUP_CAT'] = '团队'
GwLocalization['GROUP_CAT_1'] = '团队' 
GwLocalization['GROUP_DESC'] = '修改队伍和团队选项，以满足你的需求.'
GwLocalization['GROUP_TOOLTIP'] = '团队模块设置.'
GwLocalization['RAID_PARTY_STYLE'] = '团队布局的小队'
GwLocalization['CLASS_COLOR_RAID'] = '使用职业颜色'
GwLocalization['POWER_BARS_RAID'] = '显示能量条'
GwLocalization['DEBUFF_DISPELL'] = '仅显示可驱散的Debuffs'
GwLocalization['RAID_CONT_HEIGHT'] = '设置团队模块高度'
GwLocalization['RAID_BAR_WIDTH'] = '设置团员模块宽度'
GwLocalization['RAID_BAR_HEIGHT'] = '设置团员模块高度'

GwLocalization['PROFILES_CAT'] = '配置文件'
GwLocalization['PROFILES_CAT_1'] = '配置文件' 
GwLocalization['PROFILES_DESC'] = '配置文件能够在你的账号下共享配置.'
GwLocalization['PROFILES_TOOLTIP'] = '添加或删除配置文件.'
GwLocalization['PROFILES_DEFAULT_SETTINGS'] = '默认设置'
GwLocalization['PROFILES_DEFAULT_SETTINGS_PROMPT'] = '你确定要载入默认设置吗？\n\n所有以前的设置将丢失.'
GwLocalization['PROFILES_NEW_PROFILE'] = '新的配置文件'
GwLocalization['PROFILES_LOAD_BUTTON'] = '加载'
GwLocalization['PROFILES_CREATED'] = '创建于: '
GwLocalization['PROFILES_CREATED_BY'] = '\n创建者: '
GwLocalization['PROFILES_LAST_UPDATE'] = '\n最后更新: '
GwLocalization['PROFILES_DELETE'] = '你确定要删除此配置文件？' 
GwLocalization['PROFILES_MISSING_LOAD'] = '如果你看到这条消息.是因为我们忘了加载一些文本.不用担心,我们有一条像这样的示例文本来填充.' 


GwLocalization['SETTINGS_NO_LOAD_ERROR'] = '某些文本尚未加载,请尝试重载界面.'

GwLocalization['HUD_MOVE_ERR'] = '你不能在战斗中移动界面!' 


    -- 设置说明
    GwLocalization['HEALTH_GLOBE_DESC'] = '替换原始血量模块.' 
    GwLocalization['RESOURCE_DESC'] = '替换原始法力/能量模块.' 
    GwLocalization['FOCUS_FRAME_DESC'] = '替换原始焦点模块.' 
    GwLocalization['TARGET_FRAME_DESC'] = '替换原始目标模块.' 
    GwLocalization['CHAT_BUBBLES_DESC'] = '替换原始的聊天气泡.' 
    GwLocalization['MINIMAP_DESC'] = '使用GW2风格小地图.' 
    GwLocalization['QUEST_TRACKER_DESC'] = '启用修改后的任务追踪.' 
    GwLocalization['TOOLTIPS_DESC'] = '替换原始的鼠标提示.' 
    GwLocalization['CHAT_FRAME_DESC'] = '启用修改后的聊天窗口.' 
    GwLocalization['QUESTING_FRAME_DESC'] = '启用沉浸式任务视图.' 
    GwLocalization['PLAYER_AURAS_DESC'] = '移动和调整玩家的光环' 
    GwLocalization['ACTION_BARS_DESC'] = '使用GW2风格的动作条.' 
    GwLocalization['INVENTORY_FRAME_DESC'] = '启用统一的背包界面.' 
    GwLocalization['FONTS_DESC'] = '用GW2风格字体替换默认字体.' 
    GwLocalization['CASTING_BAR_DESC'] = '启用GW2风格的施法条.' 
    GwLocalization['CLASS_POWER_DESC'] = '启用修改后的连击点.' 
    GwLocalization['GROUP_FRAMES_DESC'] = '替换原始的团队模块.' 
    GwLocalization['CHRACTER_WINDOW_DESC'] = '替换原始的角色信息.' 

    GwLocalization['TARGET_OF_TARGET_DESC'] = '启用目标的目标模块.' 
    GwLocalization['HEALTH_VALUE_DESC'] = '将血量状态显示为数值.' 
    GwLocalization['HEALTH_PERCENTAGE_DESC'] = '将血量显示为百分比.' 
    GwLocalization['CLASS_COLOR_DESC'] = '将血条颜色显示为职业颜色.' 
    GwLocalization['SHOW_DEBUFFS_DESC'] = '显示你对目标造成的减益效果.' 
    GwLocalization['SHOW_ALL_DEBUFFS_DESC'] = '显示目标所有的减益效果.' 
    GwLocalization['SHOW_BUFFS_DESC'] = '显示目标的增益效果.' 

    GwLocalization['FOCUS_TARGET_DESC'] = '启用焦点目标模块.' 

    GwLocalization['ACTION_BAR_FADE_DESC'] = '离开战斗后渐隐额外的动作栏.' 
    GwLocalization['DYNAMIC_HUD_DESC'] = '启用或禁用动态变化的背景界面.' 
    GwLocalization['CHAT_FADE_DESC'] = '允许聊天栏在不使用时渐隐.' 
    GwLocalization['HIDE_EMPTY_SLOTS_DESC'] = '隐藏空动作栏位.' 
    GwLocalization['COMPASS_TOGGLE_DESC'] = '启用或禁用任务追踪指南针.' 
    GwLocalization['ADV_CAST_BAR_DESC'] = '启用或禁用高级施法条.' 
    GwLocalization['HUD_SCALE_DESC'] = '更改界面大小.' 
    GwLocalization['MINIMAP_SCALE_DESC'] = '更改小地图大小.' 

    GwLocalization['RAID_PARTY_STYLE_DESC'] = '小队模块使用团队风格.' 
    GwLocalization['CLASS_COLOR_RAID_DESC'] = '使用职业颜色代替职业图标.' 
    GwLocalization['POWER_BARS_RAID_DESC'] = '显示团队模块上的能量条.' 
    GwLocalization['DEBUFF_DISPELL_DESC'] = '只显示你能够驱散的的减益效果.' 
    GwLocalization['RAID_CONT_HEIGHT_DESC'] = '设置团队模块可以显示的最大高度.' 
    GwLocalization['RAID_BAR_WIDTH_DESC'] = '设置团员资源的宽度.' 
    GwLocalization['RAID_BAR_HEIGHT_DESC'] = '设置团员资源的高度.' 

    GwLocalization['PROFILES_DEFAULT_SETTINGS_DESC'] = '将默认设置加载到当前的配置文件.' 

    

-- 背包
GwLocalization['INVENTORY_TITLE'] = '背包'
GwLocalization['COMPACT_ICONS'] = '小图标'
GwLocalization['EXPAND_ICONS'] = '大图标'
GwLocalization['SORT_BAGS'] = '整　理'
GwLocalization['CLICK_TO_TRACK'] = '点击追踪'

-- 银行
GwLocalization['BANK_TITLE'] = '银行'
GwLocalization['REAGENT_BANK_TITLE'] = '材料银行'
GwLocalization['BANK_BUY_SLOTS'] = '购买更多栏位'
GwLocalization['REAGENT_BANK_DEPOSIT_ALL'] = '全部存入'
GwLocalization['PURCHASE_REAGENT_BANK'] = '购买 '
GwLocalization['SORT_BANK'] = '整　理'
GwLocalization['BANK_COMPACT_ICONS'] = '小图标'
GwLocalization['BANK_EXPAND_ICONS'] = '大图标'
GwLocalization['NAME_LOAD_ERROR'] = '名称无法加载'
GwLocalization['AMOUNT_LOAD_ERROR'] = '金额无法加载'

-- 角色信息
GwLocalization['CHARACTER_TITLE'] = '英雄'
GwLocalization['CHARACTER_HEADER'] = '角色信息'
GwLocalization['CHARACTER_NOT_LOADED'] = '未加载.'
GwLocalization['CHARCTER_EQUIP_OUTFIT'] = '装备'
GwLocalization['CHARACTER_SAVE_OUTFIT'] = '保存'
GwLocalization['CHARACTER_DELETE_OUTFIT'] = '删除'
GwLocalization['CHARACTER_MENU_EQUIPMENT'] = '装备'
GwLocalization['CHARACTER_MENU_OUTFITS'] = '装备管理'
GwLocalization['CHARACTER_MENU_TITLES'] = '头衔'
GwLocalization['CHARACTER_MENU_REPS'] = '声望'
GwLocalization['CHARACTER_MENU_EQUIPMENT_RETURN'] = '角色: 装备'
GwLocalization['CHARACTER_MENU_OUTFITS_RETURN'] = '角色: \n装备管理'
GwLocalization['CHARACTER_MENU_TITLES_RETURN'] = '角色: 头衔'
GwLocalization['CHARACTER_MENU_REPS_RETURN'] = '角色: 声望'
GwLocalization['CHARACTER_NAME_UNKNOWN'] = '未知'
GwLocalization['CHARACTER_STATS'] = '统计'
GwLocalization['CHARACTER_LEVEL_CLASS'] = '等级 %n 职业'
GwLocalization['CHARACTER_CURRENT_RANK'] = '当前'
GwLocalization['CHARACTER_NEXT_RANK'] = '下一个'
GwLocalization['CHARACTER_REP_SEARCH'] = '搜索...'
GwLocalization['CHARACTER_OUTFITS_SAVE'] = '你想要保存装备方案"'
GwLocalization['CHARACTER_OUTFITS_DELETE'] = '你确认要删除装备方案"'
GwLocalization['CHARACTER_REPUTATION_INACTIVE'] = '隐藏' 
GwLocalization['CHARACTER_REPUTATION_TRACK'] = '显示为经验条' 
GwLocalization['CHARACTER_OUTFIT_NEW'] = '新的方案' 
GwLocalization['CHARACTER_ATTRIBUTES'] = '属性' 
GwLocalization['CHARACTER_LEVEL'] = '等级' 

-- 界面
GwLocalization['DAMAGED_OR_BROKEN_EQUIPMENT'] = '破损的装备'
GwLocalization['LEVEL_REWARDS'] = '即将到来的等级奖励'
GwLocalization['LEVEL_REWARDS_RHEADER'] = '奖励'
GwLocalization['LEVEL_REWARDS_LHEADER'] = '等级'
GwLocalization['LEVEL_REWARDS_CLOSE'] = '关闭'
GwLocalization['LEVEL_REWARDS_TALENT'] = '天赋点数'
GwLocalization['EXP_BAR_TOOLTIP_EXP_TITLE'] = '经验'
GwLocalization['EXP_BAR_TOOLTIP_EXP_VALUE'] = '经验 '
GwLocalization['EXP_BAR_TOOLTIP_EXP_RESTING'] = ' (精力充沛)'
GwLocalization['EXP_BAR_TOOLTIP_EXP_RESTED'] = '精力充沛 '
GwLocalization['EXP_BAR_TOOLTIP_ARTIFACT'] = '\n神器: '
GwLocalization['EXP_BAR_TOOLTIP_REP'] = ' 声望 '
GwLocalization['EXP_BAR_TOOLTIP_HONOR'] = '荣誉 '
GwLocalization['GW_BAG_MICROBUTTON_STRING'] = '背包' 
GwLocalization['UPDATE_STRING_3'] = '一个 |cFFFF0000重要|r 更新可用.\n强烈建议你更新.' 
GwLocalization['UPDATE_STRING_2'] = '包含新功能的更新.' 
GwLocalization['UPDATE_STRING_1'] = '新的更新可供下载.' 
GwLocalization['FPS_TOOLTIP_1'] = '帧数 ' 
GwLocalization['FPS_TOOLTIP_2'] = '延迟 (本地) ' 
GwLocalization['FPS_TOOLTIP_3'] = '延迟 (世界) ' 
GwLocalization['MINIMAP_HOVER'] = '小地图详细信息' 
GwLocalization['MINIMAP_HOVER_TOOLTIP'] = '永久显示小地图信息.' 
GwLocalization['MINIMAP_HOVER_1'] = '隐藏信息' 
GwLocalization['MINIMAP_HOVER_2'] = '显示信息' 
GwLocalization['MINIMAP_HOVER_3'] = '显示时间' 
GwLocalization['MINIMAP_HOVER_4'] = '显示区域' 

-- 队伍
GwLocalization['PARTY_INVITE'] = '邀请'
GwLocalization['PARTY_LEAVE'] = '离开'
GwLocalization['PARTY_READY_CHECK'] = '就绪检查'
GwLocalization['PARTY_ROLE_CHECK'] = '角色检查'
GwLocalization['PARTY_CONVERT'] = '转换为团队'
GwLocalization['RAID_CONVERT'] = '转换为小队' 
GwLocalization['PARTY_INVITE_STRING'] = '玩家名字'
GwLocalization['TARGET_MARKER'] = '团队标记' 
GwLocalization['GROUND_MARKER'] = '世界标记' 

-- 任务追踪
GwLocalization['TRACKER_QUEST_TITLE'] = '任务'
GwLocalization['TRACKER_TIME_REMAINING'] = '剩余时间'
GwLocalization['TRACKER_MORE_ADVENTURES'] = '更多的冒险在等待:'
GwLocalization['TRACKER_ACHIEVEMENTS'] = '成就' 
GwLocalization['TRACKER_EVENTS'] = '事件' 

-- 任务视图
GwLocalization['QUEST_VIEW_DECLINE'] = '取消'
GwLocalization['QUEST_VIEW_SKIP'] = '继续'
GwLocalization['QUEST_VIEW_ACCPET'] = '接受'
GwLocalization['QUEST_VIEW_COMPLETE'] = '完成'

-- 地图
GwLocalization['MAP_CLOCK_TITLE'] = '时间'
GwLocalization['MAP_CLOCK_LOCAL_REALM'] = 'Shift-点击 在本地或服务器时间之间切换 '
GwLocalization['MAP_CLOCK_STOPWATCH'] = '右键点击打开秒表'
GwLocalization['MAP_CLOCK_MILITARY'] = '左键单击切换时间格式'
GwLocalization['MAP_CLOCK_DISPLAY'] = '显示: '

end


if GetLocale() == "zhCN" then
	GWUseThisLocalization()
end

-- After using this localization or deciding that we don"t need it, remove it from memory.
GWUseThisLocalization = nil

