name: Alphas

# triggers when pushing onto develop
on:
  push:
    branches:
      - develop

env:
  # for github releases, this secret is automatically provided to the workflow
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
  CF_API_KEY: ${{ secrets.CF_API_KEY }}

jobs:
  release: # "release" is a job, you can name it anything you want
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            ref: develop
        - uses: BigWigsMods/packager@master