name: Release Retail Update # description of this workflow, can be anything you want

# triggers when pushing a tag
on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Generate package changelog
          run: python3 tools/generate_changelog_txt.py changelog.lua CHANGELOG_NEW_VERSION.txt
        - uses: BigWigsMods/packager@master
          env:
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
